/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jj.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.persistence.EntityManager;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import jj.util.EntityManagerUtil;
import jj.util.FechasUtil;

/**
 *
 * @author mjapon
 */
public class BaseFrame extends javax.swing.JFrame {
    
    protected EntityManager em;

    /**
     * Creates new form BaseFrame
     */
    public BaseFrame() {
        //initComponents();
        
        em = EntityManagerUtil.createEntintyManagerFactory();
    }
    
    public void showMsgError(Throwable ex){
        JOptionPane.showMessageDialog(null, "Algo salio mal :-( "+ex.getMessage());
        System.out.println("Excepcion:"+ex.getMessage());
        ex.printStackTrace();
    }
    
    public void showMsg(String msg){
        JOptionPane.showMessageDialog(null,msg);
    }
    
    public void centerOnScreen(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-getSize().width/2, dim.height/2-getSize().height/2);
    }
    
    protected MaskFormatter createFormatter(String s) {
        MaskFormatter formatter = null;
        try {
            formatter = new MaskFormatter(s);
        } catch (java.text.ParseException exc) {
            System.err.println("formatter is bad: " + exc.getMessage());
            System.exit(-1);
        }
        return formatter;
    }
    
    protected void setupFechasEvent(JComboBox jComboBox, JFormattedTextField desdeTF, JFormattedTextField hastaTF){
        
        
        Integer fechaIndex = jComboBox.getSelectedIndex();
        switch (fechaIndex){
            case 0: //hoy
            {
                desdeTF.setText(FechasUtil.getFechaActual());
                hastaTF.setText(FechasUtil.getFechaActual());
                break;
            }
            case 1:{//ayer
                Calendar cal = Calendar.getInstance().getInstance();
                cal.set(Calendar.DAY_OF_YEAR, cal.get(Calendar.DAY_OF_YEAR)-1 );
                desdeTF.setText( FechasUtil.format(cal.getTime()) );
                hastaTF.setText( FechasUtil.format(cal.getTime()) );
                break;
            }
            case 2:{//Esta semana
                Calendar cal = Calendar.getInstance();
                cal.set(Calendar.DAY_OF_WEEK, cal.getFirstDayOfWeek());
                desdeTF.setText( FechasUtil.format(cal.getTime()));
                cal.add(Calendar.DAY_OF_WEEK, 6);
                cal.set(Calendar.DAY_OF_WEEK, cal.getFirstDayOfWeek());
                break;
            }
            case 3:{//Este mes
                Calendar cal = Calendar.getInstance();
                cal.set(Calendar.DAY_OF_MONTH, 1);
                desdeTF.setText( FechasUtil.format(cal.getTime()));

                cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
                hastaTF.setText( FechasUtil.format(cal.getTime()));
                break;
            }
            case 4:{//MES ANTERIOR
                Calendar cal = Calendar.getInstance();

                cal.set(Calendar.MONTH, cal.get(Calendar.MONTH)-1);
                cal.set(Calendar.DAY_OF_MONTH, 1);
                desdeTF.setText( FechasUtil.format(cal.getTime()));

                cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
                hastaTF.setText( FechasUtil.format(cal.getTime()));
                break;
            }
            case 5:{//ESTE AÑO
                Calendar cal = Calendar.getInstance();
                cal.set(Calendar.MONTH, cal.getActualMinimum(Calendar.MONTH));
                cal.set(Calendar.DAY_OF_MONTH, 1);
                desdeTF.setText( FechasUtil.format(cal.getTime()));

                cal.set(Calendar.MONTH, cal.getActualMaximum(Calendar.MONTH));
                cal.set(Calendar.DAY_OF_YEAR, cal.getActualMaximum(Calendar.DAY_OF_YEAR));
                hastaTF.setText( FechasUtil.format(cal.getTime()));
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
