/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jj.gui;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import jj.util.FilaPago;
import jj.util.NumbersUtil;

/**
 *
 * @author mjapon
 */
public class PagosFrame extends javax.swing.JFrame {
    
    private FacturaVentaFrame  facturaFrame;
    private BigDecimal montoEfectivo;
    private BigDecimal montoCredito;
    /**
     * Creates new form PagosFrame
     */
    public PagosFrame(FacturaVentaFrame facturaFrame) {
        initComponents();
        this.facturaFrame = facturaFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        creditoTF = new javax.swing.JTextField();
        efectivoTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        jPanelNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelSouth = new javax.swing.JPanel();
        jButtonAllCredito = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("EFECTIVO:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("CRÉDITO:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("OBSERVACIÓN:");

        creditoTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        creditoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                creditoTFFocusLost(evt);
            }
        });

        efectivoTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        efectivoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                efectivoTFFocusLost(evt);
            }
        });

        obsTextArea.setColumns(20);
        obsTextArea.setRows(5);
        jScrollPane1.setViewportView(obsTextArea);

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(efectivoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(creditoTF)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(efectivoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("FORMAS DE PAGO");
        jPanelNorth.add(jLabel1);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelSouth.setLayout(new java.awt.GridLayout(4, 1));

        jButtonAllCredito.setText("Todo ha crédito");
        jButtonAllCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllCreditoActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonAllCredito);

        jButtonCerrar.setText("Aceptar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonCerrar);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.facturaFrame.syncPagos(false);
        this.setVisible(false);        
        
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonAllCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllCreditoActionPerformed
        
        if (this.montoEfectivo != null){
            this.efectivoTF.setText( BigDecimal.ZERO.toPlainString() );        
            this.creditoTF.setText( NumbersUtil.round(montoEfectivo, 2).toPlainString() );
        }
        
    }//GEN-LAST:event_jButtonAllCreditoActionPerformed

    private void efectivoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_efectivoTFFocusLost
        
        try{            
            BigDecimal montoTotal = montoEfectivo.add(montoCredito);
            BigDecimal montoEfectivo = new BigDecimal(efectivoTF.getText());            
            if (montoEfectivo.compareTo(montoTotal)<=0){
                BigDecimal montoCredito = NumbersUtil.round(montoTotal.subtract(montoEfectivo), 2);
                this.creditoTF.setText(montoCredito.toPlainString());
            }
        }
        catch(Throwable ex){
            System.out.println("Error al calcular montos:"+ex.getMessage());
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_efectivoTFFocusLost

    private void creditoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creditoTFFocusLost
        try{            
            BigDecimal montoTotal = montoEfectivo.add(montoCredito);
            BigDecimal montoCredito = new BigDecimal(creditoTF.getText());            
            if (montoCredito.compareTo(montoTotal)<=0){
                BigDecimal montoEfectivo = NumbersUtil.round(montoTotal.subtract(montoCredito), 2);
                this.efectivoTF.setText(montoEfectivo.toPlainString());
            }
        }
        catch(Throwable ex){
            System.out.println("Error al calcular montos:"+ex.getMessage());
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_creditoTFFocusLost

    public void loadDatosPagos(BigDecimal efectivo, BigDecimal credito, String obs){        
        
        montoEfectivo = efectivo;
        montoCredito = credito;
        
        this.efectivoTF.setText( NumbersUtil.round(efectivo, 2).toPlainString() );        
        this.creditoTF.setText( NumbersUtil.round(credito, 2).toPlainString() );
        this.obsTextArea.setText(obs);
    }
    
    public Map<Integer,FilaPago> getDatosPagos(){
        Map<Integer, FilaPago> mapPagos = new HashMap<Integer, FilaPago>();
        mapPagos.put(1, new FilaPago(1, "EFECTIVO", new BigDecimal(this.efectivoTF.getText()), ""));
        mapPagos.put(2, new FilaPago(2, "CRÉDITO", new BigDecimal(this.creditoTF.getText()), this.obsTextArea.getText()));
        return mapPagos;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField creditoTF;
    private javax.swing.JTextField efectivoTF;
    private javax.swing.JButton jButtonAllCredito;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea obsTextArea;
    // End of variables declaration//GEN-END:variables
}
