/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jj.gui;

import java.awt.BorderLayout;
import javax.persistence.EntityManager;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author mjapon
 */
public class PlanCuentasFrame extends javax.swing.JFrame {
    
    private EntityManager em;
    private JFrame rootFrame;   
    //private JTree jtree1;
    
    private JTree tree;
    private DefaultMutableTreeNode root, parent1, parent2, patrimonioNode, ingresoNode, gastoNode, child,child1, child2;    

    /**
     * Creates new form PlanCuentasFrame
     */
    public PlanCuentasFrame() {
        
        initComponents();
        
        initTree();
        
    }

    
    public void initTree(){
        
        
        root = new DefaultMutableTreeNode("Cuentas");
        parent1 = new DefaultMutableTreeNode("ACTIVO");
        child = new DefaultMutableTreeNode("Vijayawada");
        child1 = new DefaultMutableTreeNode("Vizag");
        parent2 = new DefaultMutableTreeNode("PASIVO");
        child2 = new DefaultMutableTreeNode("Hyderabad");
        
        parent2 = new DefaultMutableTreeNode("PASIVO");
        
        patrimonioNode = new DefaultMutableTreeNode("PATRIMONIO");
        ingresoNode = new DefaultMutableTreeNode("INGRESOS");
        gastoNode = new DefaultMutableTreeNode("GASTOS");
        
        // Adding child nodes to parent
        parent1.add(child);
        parent1.add(child1);
        parent2.add(child2);
        
        // Adding parent nodes to root
        root.add(parent1);
        root.add(parent2);
        root.add(patrimonioNode);
        root.add(ingresoNode);
        root.add(gastoNode);
        // Adding root to JTree
        tree = new JTree(root);
        
        jPanelCenter.add(new JScrollPane(tree), BorderLayout.CENTER);
        //jScrollPane1.add(tree);
        //getContentPane().add(new JScrollPane(tree));
        pack();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelSouth = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNorth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelNorth.setPreferredSize(new java.awt.Dimension(679, 100));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("PLAN DE CUENTAS");

        javax.swing.GroupLayout jPanelNorthLayout = new javax.swing.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jButton2.setText("jButton1");
        jPanel1.add(jButton2);

        jButton3.setText("jButton1");
        jPanel1.add(jButton3);

        jPanelCenter.add(jPanel1, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JFrame getRoot() {
        return rootFrame;
    }

    public void setRoot(JFrame root) {
        this.rootFrame = root;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    // End of variables declaration//GEN-END:variables
}
