/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jj.gui.merc.unid;

import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import jj.controller.UnidadesJpaController;
import jj.gui.BaseFrame;
import jj.gui.FarmaAppMain;
import jj.util.datamodels.DefGSVCol;
import jj.util.datamodels.JTableColumn;
import jj.util.datamodels.TableHeadMouseAdapter;
import jj.util.datamodels.UnidadesDataModel;
import jj.util.datamodels.rows.FilaUnidad;

/**
 *
 * @author manuel.japon
 */
public class UnidadesFrame extends BaseFrame {
    
    private UnidadesJpaController unidadesController;
    private UnidadesDataModel unidadesDataModel;
    private List<JTableColumn> columns;
    
    /**
     * Creates new form UnidadesFrame
     */
    public UnidadesFrame() {
        initComponents();        
        unidadesController = new UnidadesJpaController(em);
        
        columns = new ArrayList<>();
        initColumns();
        
        unidadesDataModel = new UnidadesDataModel(columns, unidadesController);
        loadUnidades();
        jTable1.setModel(unidadesDataModel);        
        jTable1.getTableHeader().addMouseListener(new TableHeadMouseAdapter(jTable1, unidadesDataModel));
        
    }
    
    public void loadUnidades(){
        unidadesDataModel.loadFromDataBase();
        unidadesDataModel.fireTableDataChanged();
    }
            
    
    public void initColumns(){
        //a.uni_id, a.uni_name, a.uni_simbolo
                
        columns.add(
                new JTableColumn<FilaUnidad>(
                        "ID", 
                        0, 
                        "uni_id", 
                        Integer.class,
                        new DefGSVCol<FilaUnidad>() {
                            public Object getValueAt(FilaUnidad row, int rowIndex) {
                                return row.getUnidId();
                            }
                        }
                )
        );
        
        columns.add(
                new JTableColumn<FilaUnidad>(
                        "Nombre", 
                        1, 
                        "uni_name", 
                        String.class,
                        new DefGSVCol<FilaUnidad>() {
                            public Object getValueAt(FilaUnidad row, int rowIndex) {
                                return row.getUnidName();
                            }
                        }
                )
        );
        
        columns.add(
                new JTableColumn<FilaUnidad>(
                        "Simbolo", 
                        2, 
                        "uni_simbolo", 
                        String.class,
                        new DefGSVCol<FilaUnidad>() {
                            public Object getValueAt(FilaUnidad row, int rowIndex) {
                                return row.getUnidSymbol();
                            }
                        }
                )
        );
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("UNIDADES");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(6, 1));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Editar");
        jPanel3.add(jButton2);

        jButton4.setText("Borrar");
        jPanel3.add(jButton4);

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            JTextField nombreField = new JTextField(10);
            JTextField abrField = new JTextField(5);
            JPanel myPanel = new JPanel();
            myPanel.add(new JLabel("Nombre:"));
            myPanel.add(nombreField);
            myPanel.add(Box.createHorizontalStrut(15)); // a spacer
            myPanel.add(new JLabel("Símbolo:"));
            myPanel.add(abrField);

            int result = JOptionPane.showConfirmDialog(
                    null, 
                    myPanel,
                    "Ingrese el nombre y el símblo de la unidad", 
                    JOptionPane.OK_CANCEL_OPTION
            );
            if (result == JOptionPane.OK_OPTION) {
                String nombre = nombreField.getText();
                String abrev = abrField.getText();
                unidadesController.crear(new FilaUnidad(0, nombre, abrev));
                loadUnidades();
                FarmaAppMain.showSystemTrayMsg(" Registrado satisfactoriamente ");
            }
        }
        catch(Throwable ex){
            showMsgError(ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
